# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build data

on:
  push:
    branches: [ "feature-unificado" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: bridge
    - uses: actions/checkout@v4
      with:
        repository: socialtic/api-politica
        path: api
        ref: mexico      
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        cd bridge
        python -m pip install --upgrade pip
        echo "pip"
        pip install -r requirements.txt
        echo {   \"token_type\": \"Bearer\", \"token_value\": \"1\" } > token.json
    - name: Start api-politica
      run: |
        # stop the build if there are Python syntax errors or undefined names
        cd api
        echo "pip api"
        pip install -r requirements.txt
        echo  '${{ secrets.GCP_CREDENTIALS }}' > credentials.json
        echo {   \"token_type\": \"Bearer\", \"token_value\": \"1\" } > token.json
        python db_create.py 1 && python application.py &
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        cd ..
    - name: Correr unificada
      run: |
        cd bridge
        python pipeline.py local unificado.json
    - name: Exportar datos
      run: |
        curl -H "Authorization: Bearer 1" http://localhost:5000/export-min/ > test.json
